---
name: Pypi release

on:
  release:
    types:
      - published
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: "3.13"

      - name: Setup build packages
        run: |
          pip install build twine wheel

      - name: Build sdist/ wheel
        run: |
          python -m build --sdist
          python -m build --wheel
          python -m twine check dist/*

      - name: Upload sdist/ wheel
        uses: actions/upload-artifact@v5
        with:
          name: source-distribution
          path: dist

  test-build:
    needs: build
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        include:
          - os: ubuntu-latest
            label: linux-64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@28eb668aafebd9dede9d97c4ba1cd9989a4d0004
        with:
          pixi-version: "v0.58.0"
          environments: slim
          locked: false
          cache: true
          cache-write: false

      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: source-distribution
          path: dist

      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist

      - name: Verify dist/ wheel
        run: |
          pixi run python -m pip install dist/hydromt_fiat*.whl
          pixi run hydromt --models

  upload-testpypi:
    needs: test-build
    if: github.event_name == 'push'
    environment:
      name: testpypi
      url: https://test.pypi.org/p/hydromt-fiat
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download sdist/ wheel
        uses: actions/download-artifact@v6
        with:
          name: source-distribution
          path: dist

      - name: Publish TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  upload-pypi:
    needs: test-build
    if: ${{ github.event_name == 'release' && !github.event.act  }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/hydromt-fiat

    permissions:
      id-token: write

    steps:
      - name: Download sdist/ wheel
        uses: actions/download-artifact@v6
        with:
          name: source-distribution
          path: dist

      - name: Publish PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
